services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

  # Go Backend
  backend-go:
    build:
      context: ./backend - go
      dockerfile: Dockerfile
    container_name: go_backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/myapp?sslmode=disable
      - PYTHON_API_URL=python_backend:8000
    depends_on:
      - postgres
      - backend-python
    networks:
      - app-network

  # Python Backend
  backend-python:
    build:
      context: ./backend - python
      dockerfile: Dockerfile
    container_name: python_backend
    env_file:
      - ./backend - python/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend - python:/app
    networks:
      - app-network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL_GO=http://localhost:8080
      - NEXT_PUBLIC_API_URL_PYTHON=http://localhost:8000
    depends_on:
      - backend-go
      - backend-python
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge